### ISSUE TITLE
"Arbitrary" max file size in MtpStorage?

### ISSUE THREAD

**Issue by sirocyl** [retronx-team/mtp-server-nx#2]
https://github.com/retronx-team/mtp-server-nx/blob/661de37ca148e7cd1d79f1e19f695c4fd67d5a2e/source/main.cpp#L114

**Comment by m4xw** [comment]
So what?

**Comment by sirocyl** [comment]
Sorry, I hit enter early. :/

**Comment by sirocyl** [comment]
As I was saying - should it be increased? Or is it there for a reason?

**Comment by sirocyl** [comment]
yanno what fuck all this. sorry.

**Comment by m4xw** [comment]
It will be increased if it works sufficiently well.
There are more considerations to make.
